DELETE http://localhost:3000/api/reset

###

POST http://localhost:3000/api/register
Content-Type: application/json

{
  "teacher": "teacherken@gmail.com",
  "students": [
    "studentjon@gmail.com",
    "studenthon@gmail.com"
  ]
}
