DELETE http://localhost:3000/api/reset

###

POST http://localhost:3000/api/register
Content-Type: application/json

{
  "teacher": "teacherken@gmail.com",
  "students": [
    "commonstudent1@gmail.com",
    "commonstudent2@gmail.com",
    "student_only_under_teacher_ken@gmail.com"
  ]
}

###

POST http://localhost:3000/api/register
Content-Type: application/json

{
  "teacher": "teacherjoe@gmail.com",
  "students": [
    "commonstudent1@gmail.com",
    "commonstudent2@gmail.com"
  ]
}

###

GET http://localhost:3000/api/commonstudents?teacher=teacherken%40gmail.com

###

GET http://localhost:3000/api/commonstudents?teacher=teacherken%40gmail.com&teacher=teacherjoe%40gmail.com